apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-config
  namespace: reefops-data
spec:
  refreshPolicy: Periodic
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: openbao-seaweedfs
  target:
    name: seaweedfs-s3-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: seaweedfs
          app.kubernetes.io/part-of: reefops
          reefops.io/environment: development
      data:
        seaweedfs_s3_config: >-
          {"identities":[{"name":"reefops-development","credentials":[{"accessKey":"{{ .access_key }}","secretKey":"{{ .secret_key }}"}],"actions":["Admin","Read","Write"]},{"name":"reefops-barman-cloud","credentials":[{"accessKey":"{{ .barman_access_key }}","secretKey":"{{ .barman_secret_key }}"}],"actions":["Read:reefops-postgresql-backup","Write:reefops-postgresql-backup","List:reefops-postgresql-backup","Tagging:reefops-postgresql-backup"]}]}
  data:
    - secretKey: access_key
      remoteRef:
        key: seaweedfs/s3
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: seaweedfs/s3
        property: secret_key
    - secretKey: barman_access_key
      remoteRef:
        key: postgresql/barman-s3
        property: access_key
    - secretKey: barman_secret_key
      remoteRef:
        key: postgresql/barman-s3
        property: secret_key
