apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openbao-ingress
  namespace: reefops-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              reefops.io/openbao-access: "true"
              reefops.io/environment: development
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: reefops-secret-delivery
              reefops.io/environment: development
          podSelector:
            matchLabels:
              app.kubernetes.io/name: external-secrets
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: reefops-data
              reefops.io/environment: development
          podSelector:
            matchLabels:
              app.kubernetes.io/name: external-secrets
              app.kubernetes.io/instance: external-secrets-data
      ports:
        - protocol: TCP
          port: 8200
