apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    digest: sha256:a30f0b5196ff9033088e39e1f06348eb74fbe33f920bbf7cddf3827b4451c795
