apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-smoke-test
  namespace: reefops-secret-delivery
spec:
  refreshPolicy: Periodic
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: openbao-smoke-test
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: status
      remoteRef:
        key: eso-smoke-test
        property: status
