apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - metrics-services.yaml
  - service-monitors.yaml
  - rules.yaml
  - network-policies.yaml
  - telemetry.yaml
