apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - openbao-pki
  - openbao
  - external-secrets
  - external-secrets-openbao
  - nats-stack
  - nats-config
  - linkerd-certificates
  - linkerd-crds
  - linkerd-cni
  - linkerd-control-plane
