apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: reefops-postgresql-recovery-source
  namespace: reefops-data
  labels:
    app.kubernetes.io/name: reefops-postgresql-recovery-drill
    app.kubernetes.io/part-of: reefops
    reefops.io/environment: development
    reefops.io/lifecycle: ephemeral
spec:
  configuration:
    destinationPath: s3://reefops-postgresql-backup/
    endpointURL: http://reefops-seaweedfs-s3.reefops-data.svc:8333
    s3Credentials:
      accessKeyId:
        name: postgresql-barman-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: postgresql-barman-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
  instanceSidecarConfiguration:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
