apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:0553f0dcb0790533d95d5f31efe811687ca9164994ef1cfb3e93888d272c7b3a
  url: oci://ghcr.io/reefops/cloudnative-pg
