apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: reefops-postgresql
  namespace: reefops-data
  labels:
    app.kubernetes.io/name: reefops-postgresql
    app.kubernetes.io/part-of: reefops
    reefops.io/environment: development
spec:
  managed:
    roles:
      - name: openfga
        ensure: present
        login: true
        passwordSecret:
          name: openfga-postgresql
      - name: reefops_authorizer_owner
        ensure: present
        login: false
      - name: reefops_authorizer_migrator
        ensure: present
        login: true
        inRoles: [reefops_authorizer_owner]
        passwordSecret:
          name: authorizer-migrator-postgresql
      - name: reefops_authorizer_runtime
        ensure: present
        login: true
        passwordSecret:
          name: authorizer-postgresql
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:18-3-standard-trixie@sha256:0b3f86d55fcbafad6fcde45ca58fa816d4d37bab26abc67a4cefe16d562fd05f
  imagePullPolicy: IfNotPresent
  enableSuperuserAccess: false
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    labels:
      app.kubernetes.io/name: reefops-postgresql
      app.kubernetes.io/part-of: reefops
      reefops.io/environment: development
      reefops.io/s3-client: "true"
    annotations:
      helm.sh/resource-policy: keep
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
  storage:
    size: 20Gi
    storageClass: reefops-hostpath-retain
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  postgresql:
    parameters:
      log_connections: "on"
      log_disconnections: "on"
      log_lock_waits: "on"
      log_min_duration_statement: "1000"
      password_encryption: scram-sha-256
      ssl_min_protocol_version: TLSv1.3
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: reefops-postgresql-backup
