apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:125e2ce8ba16d6f2765dd4cc84799a5e59520172893edb5b0196c69d2dc799b4
  url: oci://ghcr.io/reefops/nats
