apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:1494ce378b6121430db69d4015debb8ac839996118fa1fd38f4f7053995c0fcf
  url: oci://ghcr.io/reefops/plugin-barman-cloud
